### ISSUE TITLE
Should skip empty lines just like `C` and `<a-C>`

### ISSUE THREAD

**Issue by max-baz** [occivink/kakoune-vertical-selection#5]
https://github.com/mawww/kakoune/pull/2172 is merged, `C` and `<a-C>` now skip empty lines. But this plugin does not. Can we make it also skip empty lines, to stay consistent with kakoune's native behavior?

`:select-vertically<ret><a-C><a-C><a-C><a-C>`

![vertical-selection-d1](https://user-images.githubusercontent.com/1177900/42468532-77a31dae-83b5-11e8-93f2-9fe806f35bd3.gif)

**Comment by occivink** [comment]
These regexes are starting to become write-only
